version: '3.1'

services:
  appdjango:
    build: 
      context: .
      dockerfile: ./docker/dockerfile
    ports:
      - "83:8000"
    restart: always

  web2:
    image: alpine
    ports:
      - "84:80"
    restart: always

  wordpress:
    image: wordpress
    ports:
      - "8777:80"  # Porta do host -> container
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
